'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

type Student={id:string;student_id:string;full_name:string;father_name?:string|null;guardian_name?:string|null;photo_url?:string|null;class_id?:string|null};
type Child=Student & {className?:string};

export default function Home(){
 const [user,setUser]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{const s=supabase();s.auth.getUser().then(async({data})=>{if(!data.user){setLoading(false);return}const {data:p,error:e}=await s.from('profiles').select('approved,role,full_name').eq('id',data.user.id).maybeSingle();if(e||!p?.approved||!['student','parent'].includes(p.role)){await s.auth.signOut();setError('Access Denied: your account is not approved for the Student / Parent Portal.');setLoading(false);return}setUser({...data.user,role:p.role,full_name:p.full_name});setLoading(false)})},[]);
 if(loading)return <main className="wrap"><div className="card login"><p>Loading portal...</p></div></main>;
 if(!user)return <Login initialError={error}/>;
 return <Dashboard user={user}/>;
}

function Dashboard({user}:{user:any}){const [children,setChildren]=useState<Child[]>([]);const [selected,setSelected]=useState('');const [attendance,setAttendance]=useState<any[]>([]);const [results,setResults]=useState<any[]>([]);const [announcements,setAnnouncements]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{load()},[user.id]);
 async function load(){const s=supabase();setLoading(true);setError('');try{let list:Child[]=[];if(user.role==='student'){const {data,e}=await s.from('students').select('id,student_id,full_name,father_name,guardian_name,photo_url,class_id,classes(name,section)').eq('user_id',user.id).maybeSingle();if(e)throw e;if(data)list=[{...data,className:(data as any).classes?`${(data as any).classes.name} / ${(data as any).classes.section}`:''}]}else{const {data:p,e}=await s.from('parents').select('id').eq('user_id',user.id).maybeSingle();if(e)throw e;if(p){const {data:links,e:le}=await s.from('parent_student_links').select('student_id,approved,students(id,student_id,full_name,father_name,guardian_name,photo_url,class_id,classes(name,section))').eq('parent_id',p.id).eq('approved',true);if(le)throw le;list=(links||[]).map((x:any)=>({...x.students,className:x.students?.classes?`${x.students.classes.name} / ${x.students.classes.section}`:''})).filter(Boolean)}}setChildren(list);const child=list[0];if(child)setSelected(child.id);if(child){const [a,r,n]=await Promise.all([s.from('attendance').select('attendance_date,status,note').eq('student_id',child.id).order('attendance_date',{ascending:false}).limit(31),s.from('results').select('marks_obtained,total_marks,grade,position,pass,published,exams(name,exam_date),subjects(name)').eq('student_id',child.id).eq('published',true).order('created_at',{ascending:false}).limit(50),s.from('announcements').select('id,title,body,published_at').eq('published',true).order('published_at',{ascending:false}).limit(5)]);if(a.error)throw a.error;if(r.error)throw r.error;if(n.error)throw n.error;setAttendance(a.data||[]);setResults(r.data||[]);setAnnouncements(n.data||[])}else{setAttendance([]);setResults([]);const {data:n}=await s.from('announcements').select('id,title,body,published_at').eq('published',true).order('published_at',{ascending:false}).limit(5);setAnnouncements(n||[])}}catch(e:any){setError(e?.message||'Unable to load portal data.')}finally{setLoading(false)}}
 async function changeChild(id:string){setSelected(id);const s=supabase();const [a,r]=await Promise.all([s.from('attendance').select('attendance_date,status,note').eq('student_id',id).order('attendance_date',{ascending:false}).limit(31),s.from('results').select('marks_obtained,total_marks,grade,position,pass,published,exams(name,exam_date),subjects(name)').eq('student_id',id).eq('published',true).order('created_at',{ascending:false}).limit(50)]);setAttendance(a.data||[]);setResults(r.data||[])}
 const present=attendance.filter(x=>x.status==='present').length;const attendancePct=attendance.length?Math.round((present/attendance.length)*100):0;const total=results.reduce((a,x)=>a+Number(x.total_marks||0),0);const obtained=results.reduce((a,x)=>a+Number(x.marks_obtained||0),0);const overall=total?Math.round(obtained/total*100):0;const child=children.find(x=>x.id===selected)||children[0];
 return <main className="wrap"><div className="nav"><div><div className="brand">🏫 Noble Public School Dadu</div><div className="muted">Student / Parent Portal</div></div><button className="btn" onClick={()=>supabase().auth.signOut().then(()=>location.reload())}>Logout</button></div>{user.role==='parent'&&children.length>1&&<div className="card section"><label>Select Child</label><select className="input" value={selected} onChange={e=>changeChild(e.target.value)}>{children.map(c=><option key={c.id} value={c.id}>{c.full_name} — {c.student_id}</option>)}</select></div>}{error&&<div className="alert">{error}</div>}{loading?<div className="card section"><p>Loading your school data...</p></div>:<>{child&&<div className="card"><div className="row"><div><h2>{child.full_name}</h2><p className="muted">Student ID: {child.student_id} {child.className&&`• ${child.className}`}</p></div><span className="badge">{user.role==='parent'?'Parent account':'Student account'}</span></div></div>}<div className="grid section"><Stat title="Attendance" value={attendance.length?`${attendancePct}%`:'—'}/><Stat title="Published Results" value={String(results.length)}/><Stat title="Overall Performance" value={total?`${overall}%`:'—'}/><Stat title="Announcements" value={String(announcements.length)}/></div><div className="card section"><div className="row"><h2>Recent Attendance</h2><span className="badge">Last 31 records</span></div>{attendance.length?<div>{attendance.slice(0,10).map(x=><p key={x.attendance_date}><strong>{x.attendance_date}</strong> — {x.status}{x.note?` — ${x.note}`:''}</p>)}</div>:<p className="muted">No attendance records published yet.</p>}</div><div className="card section"><h2>Published Results</h2>{results.length?<div>{results.slice(0,10).map((x,i)=><p key={i}><strong>{(x.exams as any)?.name||'Exam'}</strong> — {(x.subjects as any)?.name||'Subject'}: {x.marks_obtained ?? '—'} / {x.total_marks ?? '—'} {x.grade?`• Grade ${x.grade}`:''}</p>)}</div>:<p className="muted">No published results yet.</p>}</div><div className="card section"><h2>Announcements</h2>{announcements.length?announcements.map(x=><div key={x.id} className="section"><strong>{x.title}</strong><p>{x.body}</p></div>):<p className="muted">No announcements yet.</p>}</div></>}</main>}
function Stat({title,value}:{title:string,value:string}){return <div className="card"><div className="muted">{title}</div><div className="stat">{value}</div></div>}
function Login({initialError=''}:{initialError?:string}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState(initialError);const [busy,setBusy]=useState(false);async function submit(e:any){e.preventDefault();setError('');setBusy(true);const s=supabase();const {data,error:authError}=await s.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(authError){setBusy(false);setError('Invalid email or password. Please use the Student/Parent account credentials provided by the school.');return}const {data:profile,error:profileError}=await s.from('profiles').select('approved,role').eq('id',data.user.id).maybeSingle();if(profileError||!profile?.approved||!['student','parent'].includes(profile.role)){await s.auth.signOut();setBusy(false);setError('Access Denied: your account is not approved for the Student / Parent Portal. Please contact the school admin.');return}location.reload()}
 return <main className="wrap"><div className="card login"><h1>Noble Public School Dadu</h1><p className="muted">Student / Parent Portal</p><form onSubmit={submit}><label>Email</label><input className="input" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="student@example.com or parent@example.com"/><label>Password</label><input className="input" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/>{error&&<div className="alert">{error}</div>}<button className="btn full" type="submit" disabled={busy}>{busy?'Checking account...':'Login'}</button></form><p className="muted">Only school-approved Student and Parent accounts can access this portal.</p></div></main>}
